version: '3.8'

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./config:/mnt/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/tmp
    command: --config.file=/mnt/config/promtail.yaml
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  promtail-data:

networks:
  monitoring:
    driver: bridge
